types=amr.types
resDir=.
specmap=amr.specmap
stanfordModel=stanford-models/english-bidirectional-distsim.tagger
#verbose=true
#nerTranslation=amr.ner
#nerConfig=IllinoisNER.config
gBeam=200
resDir=.
#log=DEBUG
#sloppy=true
propBank=propbank
bankParser=easyccg
superTagger=easyccg

type=easyccg id=easyccg model=easyccg-model-rebank unaryRules=easyccg-model-rebank/unaryRules extraCombinators=easyccg-model-rebank/binaryRules seenRules=easyccg-model-rebank/seenRules nBest=5
include=parser.inc
